version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bae
      MYSQL_DATABASE: libreria
    ports:
      - "3306:3306"
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8100:8080
